AWSTemplateFormatVersion: '2010-09-09'
Description: 'photo_processor Sample SAM Template for photo_processor

  '
Globals:
  Function:
    Timeout: 10
Outputs:
  PhotoProcessorFunction:
    Description: Photo Processor Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PhotoProcessorFunction
      - Arn
  PhotoProcessorFunctionIamRole:
    Description: IAM Role created for Photo Processor function
    Value:
      Fn::GetAtt:
      - PhotoProcessorFunctionIamRole
      - Arn
Parameters:
  S3UserfilesBucketArn:
    Type: String
Resources:
  BucketPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PhotoProcessorFunction
      Principal: s3.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Ref: S3UserfilesBucketArn
    Type: AWS::Lambda::Permission
  PhotoProcessorFunction:
    Properties:
      CodeUri: s3://sam-deployment-ok/b29f07d87ad3d2eea543cd8b7db58317
      Environment:
        Variables:
          THUMBNAIL_HEIGHT: 80
          THUMBNAIL_WIDTH: 80
      Handler: app.handler
      Role:
        Fn::GetAtt:
        - PhotoProcessorFunctionIamRole
        - Arn
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PhotoProcessorFunctionIamRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: s3:*
            Effect: Allow
            Resource:
              Fn::Join:
              - /
              - - Ref: S3UserfilesBucketArn
                - '*'
          Version: '2012-10-17'
        PolicyName: AllPrivsForPhotoAlbumUserfilesBucket
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
